[versions]
agp = "8.2.2"
kotlin = "2.0.10"
okhttp = "5.0.0-alpha.14"
ktor = "3.0.0-beta-2"
kotlinx-serialization = "1.7.1"
firebase-bom = "33.7.0"
androidx-paging = "3.3.5"
room = "2.6.1"
media3 = "1.5.1"
hilt = "2.48.1"
coil = "3.0.0-rc01"
junit = "4.13.2"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.0" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.2" }
swiperefresh = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.1.0" }

fragment = { module = "androidx.fragment:fragment-ktx", version = "1.6.2" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version = "2.8.7" }

paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "androidx-paging" }
paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }

preference = { module = "androidx.preference:preference-ktx", version = "1.2.1" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
media3-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }

splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
palette = { module = "androidx.palette:palette-ktx", version = "1.0.0" }

material = { module = "com.google.android.material:material", version = "1.13.0-alpha09" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

pikolo = { module = "com.github.madrapps:pikolo", version = "2.0.2" }
fadingedgelayout = { module = "com.github.bosphere.android-fadingedgelayout:fadingedgelayout", version = "1.0.0" }
fastscroll = { module = "me.zhanghai.android.fastscroll:library", version = "1.3.0" }
kenburnsview = { module = "com.flaviofaria:kenburnsview", version = "1.0.7" }
nestedscrollwebview = { module = "com.telefonica:nestedscrollwebview", version = "0.1.6" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }

plugger = { module = "com.github.jeelpatel231:plugger", version = "82e00ea5a4" }
ktor-utils = { module = "io.ktor:ktor-utils", version.ref = "ktor" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gms = { id = "com.google.gms.google-services", version = "4.4.2" }
crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.2" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version = "2.0.10-1.0.24" }

[bundles]
paging = ["paging-common", "paging-runtime"]
media3 = ["media3-exoplayer", "media3-session", "media3-ui", "media3-dash", "media3-hls"]
coil = ["coil", "coil-network-okhttp"]